'use strict'

const plugin = require('../')
const expect = require('expect')
const path   = require('path')
const fs     = require('fs')

function concat (name, subdir) {
  let file = path.join(__dirname, subdir || 'expected', name)

  file = file.replace(/\\/g, '/')
  if (!path.extname(file)) file += '.js'
  return file
}

process.chdir(__dirname)

function merge (dest, src) {
  for (let p in src) {
    if (src.hasOwnProperty(p)) dest[p] = src[p]
  }
  return src
}

function testLines (code, expected, lines) {
  let options = { comments: 'all', functions: false, debuggerStatements: false }
  let result
  if (lines != null) {
    if (typeof lines == 'object') merge(options, lines)
    else options.maxEmptyLines = lines
  }
  result = plugin(options).transform(code, 'test.js')
  expect(result == null ? null : result.code).toBe(expected)
}

function testFile (file, opts, save) {
  let fname  = concat(file, 'fixtures')
  let expected = fs.readFileSync(concat(file), 'utf8')
  let code   = fs.readFileSync(fname, 'utf8')

  let result = plugin(opts).transform(code, fname)
  if (save) fs.writeFileSync(concat(file + '_out'), result.code, 'utf8')

  expect(result == null ? null : result.code).toBe(expected)
}

describe('rollup-plugin-cleanup', () => {

  const emptyLines10 = '\n\n\n\n\n\n\n\n\n\n'
  const emptyLinesTop = emptyLines10 + 'X'
  const emptyLinesBottom = 'X' + emptyLines10
  const emptyLinesMiddle = emptyLines10 + 'X' + emptyLines10 + 'X' + emptyLines10

  it('by default removes all the empty lines and normalize to unix', () => {
    testLines([
      '',
      'abc ',
      'x\t',
      '\r\ny \r',
      '\n\n\r\t',
      'z '
    ].join('\n'), 'abc\nx\ny\nz')
  })

  it('do not touch current indentation of non-empty lines', () => {
    testLines('  \n X\n  X ', ' X\n  X')
  })

  it('has fine support for empty lines with `maxEmptyLines`', () => {
    testLines(emptyLinesTop, 'X')
    testLines(emptyLinesBottom, 'X\n')

    testLines(emptyLinesTop, '\nX', 1)
    testLines(emptyLinesBottom, 'X\n\n', 1)
    testLines(emptyLinesMiddle, '\nX\n\nX\n\n', 1)

    testLines(emptyLinesTop, '\n\n\nX', 3)
    testLines(emptyLinesBottom, 'X\n\n\n\n', 3)
    testLines(emptyLinesMiddle, '\n\n\nX\n\n\n\nX\n\n\n\n', 3)
  })

  it('can keep all the lines by setting `maxEmptyLines` = -1', () => {
    testLines(emptyLinesTop, null, -1)
    testLines(emptyLinesBottom, null, -1)
    testLines(emptyLinesMiddle, null, -1)
  })

  it('can convert to Windows line-endings with `normalizeEols` = "win"', () => {
    const opts = { maxEmptyLines: 1, normalizeEols: 'win' }
    testLines(emptyLinesTop, '\r\nX', opts)
    testLines(emptyLinesBottom, 'X\r\n\r\n', opts)
    testLines(emptyLinesMiddle, '\r\nX\r\n\r\nX\r\n\r\n', opts)
  })

  it('and convertion to Mac line-endings with `normalizeEols` = "mac"', () => {
    const opts = { maxEmptyLines: 1, normalizeEols: 'mac' }
    testLines(emptyLinesTop, '\rX', opts)
    testLines(emptyLinesBottom, 'X\r\r', opts)
    testLines(emptyLinesMiddle, '\rX\r\rX\r\r', opts)
  })

  it('makes normalization to the desired `normalizeEols` lines', () => {
    const opts = { maxEmptyLines: -1, normalizeEols: 'mac' }
    testLines('\r\n \n\r \r\r\n \r\r \n', '\r\r\r\r\r\r\r\r', opts)
  })
})


describe('removing comments', () => {
  it('with some defaults', () => {
    testFile('defaults', {
      comments: ['some', 'eslint']
    })
  })

  /*
  it('in html inside JS (non-default)', () => {
    testFile('html-comms', {
      comments: ['some', 'eslint', 'html']
    }, true)
  })*/
})


describe('SourceMap support', () => {

  let rollup = require('rollup').rollup

  it('test bundle generated by rollup w/inlined sourcemap', () => {
    return rollup({
      entry: concat('bundle-src.js', 'maps'),
      sourceMap: true,
      plugins: [
        plugin({
          comments: ['some', 'eslint']
        })
      ]
    }).then(function (bundle) {
      let result = bundle.generate({
        format: 'iife',
        indent: true,
        moduleName: 'myapp',
        sourceMap: 'inline',
        sourceMapFile: 'maps/bundle.js', // generates sorce filename w/o path
        banner: '/*\n plugin version 1.0\n*/',
        footer: '/* follow me on Twitter! @amarcruz */'
      })
      let code = result.code + '\n//# source' + 'MappingURL=' + result.map.toUrl()

      /*
        If you modified the source in maps/bundle-src.js, you
        need to write the bundle and test it in the browser again.
      */
      //console.log('\t--- writing bundle with inlined sourceMap...')
      //fs.writeFileSync(concat('bundle', 'maps'), code, 'utf8')

      let expected = fs.readFileSync(concat('bundle', 'maps'), 'utf8')
      expect(code).toBe(expected, 'Genereted code is incorrect!')
    })
  })
})
